name: Django CI

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install --upgrade wheel
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django Testing
      run: |
        python manage.py test
    - name: Deploy to Heroku
      if: github.ref == 'refs/heads/main' && job.status == 'success'
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
         heroku_api_key: 'c9cfff6d-5292-46d8-ac3a-57cc01a13bc5'
         heroku_app_name: 'soccer2021'
         heroku_email: 'gdde007@gmail.com'

      

        


