name: Django CI

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.12
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
         heroku_api_key: 'c9cfff6d-5292-46d8-ac3a-57cc01a13bc5'
         heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
         heroku_email: 'gdde007@gmail.com'

      

        


